create DATABASE ETRADE3;
USE ETRADE3;
CREATE DATABASE IF NOT EXISTS ETRADE3;
USE ETRADE3;

CREATE TABLE USERS (
ID       		INT  AUTO_INCREMENT PRIMARY KEY,
USERNAME	  	VARCHAR(50) NOT NULL,
PASSWORD_   	VARCHAR(50) NOT NULL,
NAMESURNAME		VARCHAR(50),
EMAIL  			VARCHAR(50),
GENDER 			VARCHAR(1),
BIRTHDATE    	DATE,
CREATEDDATE		DATETIME,
TELNR1  		VARCHAR(20),
TELNR2 			VARCHAR(20)
);


CREATE TABLE ADDRESS (
ID 				INT  AUTO_INCREMENT PRIMARY KEY,
USERID   		INT,
COUNTRYID		TINYINT,
CITYID 			SMALLINT,
TOWNID 			INT,
DISTRICTID	 	INT,
POSTALCODE		VARCHAR(10),
ADDRESSTEXT 	VARCHAR(500),

CONSTRAINT 		fk_address_user
FOREIGN KEY		(USERID)
REFERENCES		USERS(ID),

CONSTRAINT 		fk_address_country
FOREIGN KEY 	(COUNTRYID)
REFERENCES		COUNTRIES(ID),

CONSTRAINT		fk_address_city
FOREIGN KEY		(CITYID)
REFERENCES		CITIES(ID),

CONSTRAINT 		fk_address_town
FOREIGN KEY		(TOWNID)
REFERENCES		TOWNS(ID),

CONSTRAINT		fk_address_district
FOREIGN KEY 	(DISTRICTID)
REFERENCES		DISTRICTS(ID)
);

CREATE TABLE COUNTRIES (
ID 				TINYINT AUTO_INCREMENT PRIMARY KEY,
COUNTRY 		VARCHAR (50) NOT NULL
);

CREATE TABLE CITIES (
ID 				SMALLINT  AUTO_INCREMENT PRIMARY KEY,
COUNTRYID  		TINYINT ,
CITY  			VARCHAR(50) NOT NULL,

CONSTRAINT 		fk_city_country
FOREIGN KEY 	(COUNTRYID)
REFERENCES		COUNTRIES(ID)
ON DELETE		CASCADE
);

CREATE TABLE TOWNS (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
CITYID 			SMALLINT,
TOWN 			VARCHAR(50),

CONSTRAINT 		fk_town_city
FOREIGN KEY		(CITYID)
REFERENCES		CITIES(ID)
ON DELETE		CASCADE
);

CREATE TABLE DISTRICTS (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
TOWNID  		INT,
DISTRICT  		VARCHAR(50),
CONSTRAINT 		fk_district_town
FOREIGN KEY		(TOWNID)
REFERENCES		TOWNS(ID)
ON DELETE		CASCADE
);

CREATE TABLE ITEMS (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
ITEMCODE 		VARCHAR(50),
ITEMNAME		VARCHAR(100),
UNITPRICE		FLOAT,
CATEGORY1		VARCHAR(50),
CATEGORY2		VARCHAR(50),
CATEGORY3		VARCHAR(50),
CATEGORY4		VARCHAR(50),
BRAND			VARCHAR(50)
);

CREATE TABLE PAYMENTS (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
ORDERID			INT,
PAYMENTTYPE		TINYINT,
DATE_			DATETIME,
ISOK			BIT,
APPROVECODE		VARCHAR(100),
PAYMENTTOTAL	FLOAT,

CONSTRAINT		fk_payment_order
FOREIGN KEY		(ORDERID)
REFERENCES		ORDERS(ID)
);

CREATE TABLE ORDERS (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
USERID			INT,
DATE_ 			DATETIME,
TOTALPRICE		FLOAT,
STATUS_			TINYINT,
ADDRESSID		INT,

CONSTRAINT 		fk_order_user
FOREIGN KEY		(USERID)
REFERENCES		USERS(ID),

CONSTRAINT		fk_order_address
FOREIGN KEY 	(ADDRESSID)
REFERENCES		ADDRESS(ID)
);

CREATE TABLE ORDERDETAILS (
ID				INT AUTO_INCREMENT PRIMARY KEY,
ORDERID			INT,
ITEMID			INT,
AMOUNT			INT,
UNITPRICE		FLOAT,
LINETOTAL		FLOAT,

CONSTRAINT		fk_orderdetail_order
FOREIGN KEY		(ORDERID)
REFERENCES		ORDERS(ID),

CONSTRAINT 		fk_orderdetail_item
FOREIGN KEY		(ITEMID)
REFERENCES		ITEMS(ID)
);

CREATE TABLE INVOICES (
ID 				INT AUTO_INCREMENT PRIMARY KEY,
ORDERID			INT,
DATE_			DATETIME,
ADDRESSID 		INT,
CARGOFICHENO	VARCHAR(20),
TOTALPRICE		FLOAT,

CONSTRAINT		fk_invoices_order
FOREIGN KEY		(ORDERID)
REFERENCES		ORDERS(ID),

CONSTRAINT		fk_invoices_address
FOREIGN KEY		(ADDRESSID)
REFERENCES		ADDRESS(ID)
);

CREATE TABLE INVOICEDETAILS (
ID				INT AUTO_INCREMENT PRIMARY KEY,
INVOICEID		INT,
ORDERDETAILID	INT,
ITEMID			INT,
AMOUNT			INT,
UNITPRICE		FLOAT,

CONSTRAINT 		fk_invoicedetail_invoice
FOREIGN KEY		(INVOICEID)
REFERENCES		INVOICES(ID),

CONSTRAINT 		fk_invoicedetail_orderdetail
FOREIGN KEY		(ORDERDETAILID)
REFERENCES		ORDERS(ID),

CONSTRAINT		fk_invoicedetail_item
FOREIGN KEY		(ITEMID)
REFERENCES		ITEMS(ID)
);



























